use wasm_bindgen::prelude::*;

// --- COMPARISON WITH SERVER-SIDE (Spin) ---
//
// Server (src/lib.rs):
//   #[http_component]           <-- Spin macro: "run this when an HTTP request arrives"
//   async fn handle(req) -> Response
//
// Browser (this file):
//   #[wasm_bindgen]             <-- wasm-bindgen macro: "expose this to JavaScript"
//   pub fn greet() -> String
//
// Key difference:
//   Server = reactive (waits for requests, sends responses)
//   Browser = callable (JavaScript calls your Rust functions directly)

/// This function is callable from JavaScript.
/// In JS you'd write: wasm.greet("World") and get back a String.
#[wasm_bindgen]
pub fn greet(name: &str) -> String {
    format!(
        "Hello, {}! This greeting was generated by Rust running as WASM in your browser.",
        name
    )
}

/// This function directly manipulates the DOM from Rust.
/// No JavaScript needed — Rust talks to browser APIs via web-sys.
#[wasm_bindgen]
pub fn add_greeting_to_page(name: &str) {
    // web_sys::window() is like `window` in JavaScript
    let window = web_sys::window().expect("no window");
    let document = window.document().expect("no document");
    let body = document.body().expect("no body");

    let el = document.create_element("p").expect("can't create <p>");
    el.set_text_content(Some(&greet(name)));
    el.set_attribute("style", "font-family: monospace; padding: 8px; background: #e8f5e9; border-radius: 4px; margin: 8px 0;")
        .expect("can't set style");

    body.append_child(&el).expect("can't append");
}

/// Logs to the browser's developer console (like console.log in JS).
#[wasm_bindgen]
pub fn log_to_console(msg: &str) {
    web_sys::console::log_1(&msg.into());
}

/// Returns a timestamp to demonstrate passing data between Rust and JS.
/// Rust does the computation, JS displays it.
#[wasm_bindgen]
pub fn fibonacci(n: u32) -> u64 {
    // This runs at near-native speed in the browser!
    // Great for CPU-heavy tasks that would be slow in JavaScript.
    match n {
        0 => 0,
        1 => 1,
        _ => {
            let mut a: u64 = 0;
            let mut b: u64 = 1;
            for _ in 2..=n {
                let tmp = a + b;
                a = b;
                b = tmp;
            }
            b
        }
    }
}
